name: demo

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: stop the app
      run: New-Item -Path C:\Websites\demo.blogifier.net\_work\Blogifier\Blogifier\release -Name "app_offline.htm" -ItemType "file"

    - name: Publish Blogifier
      run: dotnet publish -c Release -o release --nologo

    - name: start the app
      run: Remove-Item -Path C:\Websites\demo.blogifier.net\_work\Blogifier\Blogifier\release\app_offline.htm
