name: demo

on:
  push:
    branches:
      - demo

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build The Demo
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DEMO_HOST_SECRET }}
          username: ${{ secrets.DEMO_USER_SECRET }}
          password: ${{ secrets.DEMO_PASS_SECRET }}
          command: |
            & "c:/github/demo.ps1"
